name: Tutor Build Action

on:
  push:
    branches:
      - 'vue/actions-tests'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Get current time
        uses: josStorer/get-current-time@v2
        id: current-time
        with:
          format: YYYY-MM-DD-HH-mm
      - name: Build Image
        uses: Pearson-Advance/tutor-build-image-action@v1.0.0
        with:
          python-version: ${{ vars.BUILD_PYTHON_VERSION }}
          tutor-version: ${{ vars.BUILD_TUTOR_VERSION }}
          path-image-to-be-built: 'env/plugins/discovery/build/discovery'
          organization-name: ${{ vars.BUILD_ORGANIZATION_NAME }}
          repository-name: ${{ vars.BUILD_REPOSITORY_NAME }}
          image-tag: ${{ vars.DISCOVERY_TUTOR_PLUGIN_VERSION }}-${{ steps.current-time.outputs.formattedTime }}
          docker-username: ${{ secrets.DOCKERHUB_USERNAME }}
          docker-token: ${{ secrets.DOCKERHUB_TOKEN }}
          use-docker-cache: ${{ vars.BUILD_USE_CACHE }}
          tutor-plugin-sources: '("git+https://github.com/overhangio/tutor-discovery.git@v${{ vars.DISCOVERY_TUTOR_PLUGIN_VERSION }}")'
          tutor-plugin-names: '("discovery")'
          tutor-pearson-plugin-url: ${{ vars.TUTOR_PEARSON_PLUGIN_URL }}
          tutor-pearson-plugin-name: 'pearson-plugin-discovery-prod'
          gh-access-token: ${{ secrets.GH_ACCESS_TOKEN }}
